### ISSUE TITLE
Provide Source Code

### ISSUE THREAD

**Issue by jsuleder** [MilosKozak/danars-support-lib#2]
Hi! 
Is it possible to provide the source code for the binaries? Many legacy encryption systems used to rely on obscurity of the algorithm. This is a bad approach, as you have to keep the whole program secret, which basically isn't given anymore as the program is distributed and its algorithm could be reversed with more or less effort. Nevertheless, being able to review the source code would be much easier.
Thanks four your response!

**Comment by MilosKozak** [comment]
Hi, what do you need the source code for? But it's not our decision anyway

**Comment by jsuleder** [comment]
I want to review the encryption and decryption of the bluetooth packages. Okay, so where did you get the binary from?

**Comment by MilosKozak** [comment]
SOOIL

**Comment by MilosKozak** [comment]
But this library has nothing to do with BT encryption. It encrypts only data packets

**Comment by jsuleder** [comment]
Well, it decrypts and encrypts the packets received and sent via Bluetooth so basically satisfies our needs. I will contact SOOIL. Thanks!
